<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Annie Cao (ID: 2599315)">
<meta name="author" content="Vicki Wang (ID: 2581225)">
<meta name="author" content="Yan Yang (ID: 2610419)">
<meta name="author" content="Gloria Wang (2550999)">

<title>Two Decades of Educational Change: Global Enrollment Trends and Gender Gap Reduction, 2000–2020</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="final_report_files/libs/clipboard/clipboard.min.js"></script>
<script src="final_report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="final_report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="final_report_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="final_report_files/libs/quarto-html/popper.min.js"></script>
<script src="final_report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="final_report_files/libs/quarto-html/anchor.min.js"></script>
<link href="final_report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="final_report_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="final_report_files/libs/quarto-html/quarto-syntax-highlighting-dark-707d8167ce6003fca903bfe2be84ab7f.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="final_report_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="final_report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="final_report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="final_report_files/libs/bootstrap/bootstrap-04024d98dd357bb9fdc27c45f27003da.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="final_report_files/libs/bootstrap/bootstrap-dark-a059cd785a54d942fe52cc116ee70b23.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="final_report_files/libs/bootstrap/bootstrap-04024d98dd357bb9fdc27c45f27003da.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#data-description-cleaning" id="toc-data-description-cleaning" class="nav-link" data-scroll-target="#data-description-cleaning"><span class="header-section-number">2</span> Data Description &amp; Cleaning</a>
  <ul class="collapse">
  <li><a href="#removal-of-missing-values" id="toc-removal-of-missing-values" class="nav-link" data-scroll-target="#removal-of-missing-values"><span class="header-section-number">2.1</span> Removal of Missing Values</a></li>
  <li><a href="#standardizing-indicator-labels" id="toc-standardizing-indicator-labels" class="nav-link" data-scroll-target="#standardizing-indicator-labels"><span class="header-section-number">2.2</span> Standardizing Indicator Labels</a></li>
  <li><a href="#filtering-to-target-regions" id="toc-filtering-to-target-regions" class="nav-link" data-scroll-target="#filtering-to-target-regions"><span class="header-section-number">2.3</span> Filtering to Target Regions</a></li>
  <li><a href="#converting-to-long-format" id="toc-converting-to-long-format" class="nav-link" data-scroll-target="#converting-to-long-format"><span class="header-section-number">2.4</span> Converting to Long Format</a></li>
  <li><a href="#exporting-final-dataset" id="toc-exporting-final-dataset" class="nav-link" data-scroll-target="#exporting-final-dataset"><span class="header-section-number">2.5</span> Exporting Final Dataset</a></li>
  </ul></li>
  <li><a href="#data-analysis-and-interpretation" id="toc-data-analysis-and-interpretation" class="nav-link" data-scroll-target="#data-analysis-and-interpretation"><span class="header-section-number">3</span> Data Analysis and Interpretation</a>
  <ul class="collapse">
  <li><a href="#growth-across-education-levels-by-region" id="toc-growth-across-education-levels-by-region" class="nav-link" data-scroll-target="#growth-across-education-levels-by-region"><span class="header-section-number">3.1</span> Growth Across Education Levels by Region</a></li>
  <li><a href="#enrollment-trends-over-time-across-regions-20002020" id="toc-enrollment-trends-over-time-across-regions-20002020" class="nav-link" data-scroll-target="#enrollment-trends-over-time-across-regions-20002020"><span class="header-section-number">3.2</span> Enrollment Trends Over Time Across Regions (2000–2020)</a></li>
  <li><a href="#gender-parity-in-educational-participation" id="toc-gender-parity-in-educational-participation" class="nav-link" data-scroll-target="#gender-parity-in-educational-participation"><span class="header-section-number">3.3</span> Gender Parity in Educational Participation</a></li>
  </ul></li>
  <li><a href="#results-and-discussion" id="toc-results-and-discussion" class="nav-link" data-scroll-target="#results-and-discussion"><span class="header-section-number">4</span> Results and Discussion</a>
  <ul class="collapse">
  <li><a href="#regional-growth-in-enrollment-20002020" id="toc-regional-growth-in-enrollment-20002020" class="nav-link" data-scroll-target="#regional-growth-in-enrollment-20002020"><span class="header-section-number">4.1</span> <strong><em>Regional Growth in Enrollment (2000–2020)</em></strong></a></li>
  <li><a href="#enrollment-convergence-relative-to-the-world-average" id="toc-enrollment-convergence-relative-to-the-world-average" class="nav-link" data-scroll-target="#enrollment-convergence-relative-to-the-world-average"><span class="header-section-number">4.2</span> <strong><em>Enrollment Convergence Relative to the World Average</em></strong></a></li>
  <li><a href="#gender-parity-in-educational-participation-1" id="toc-gender-parity-in-educational-participation-1" class="nav-link" data-scroll-target="#gender-parity-in-educational-participation-1"><span class="header-section-number">4.3</span> <strong><em>Gender Parity in Educational Participation</em></strong></a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">5</span> Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">6</span> References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="final_report.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Two Decades of Educational Change: Global Enrollment Trends and Gender Gap Reduction, 2000–2020</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Annie Cao (ID: 2599315) </p>
             <p>Vicki Wang (ID: 2581225) </p>
             <p>Yan Yang (ID: 2610419) </p>
             <p>Gloria Wang (2550999) </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Over the past twenty years, global reports have consistently highlighted that access to education remains uneven across many regions of the world. Earlier analyses consistently showed that developing countries lagged behind global averages in school enrollment, including when examining male and female participation separately.</p>
<p>We focus on five major world regions:</p>
<p>1. <strong>East Asia &amp; Pacific</strong></p>
<p>2. <strong>Latin America &amp; Caribbean</strong></p>
<p>3. <strong>The Middle East &amp; North Africa (including Afghanistan and Pakistan)</strong></p>
<p>4. <strong>South Asia</strong></p>
<p>5. <strong>Sub-Saharan Africa</strong></p>
<p>We choose these regions because these areas have historically exhibited the most pronounced educational inequalities and have been the primary focus of development assistance and policy reforms. These regions encompass a substantial share of the global population and represent contexts where expanded schooling is expected to have the greatest long-term social and economic impact.</p>
<p>Although several of these regions, such as East Asia &amp; Pacific, have substantially increased public investment in schooling and improved educational attainment, it remains unclear whether these advances have led to true convergence toward global norms. This motivates our first research question: <strong><em>Have enrollment rates in these five regions converged toward the world average from 2000 to 2020 across primary, secondary, and tertiary education?</em></strong></p>
<p>Achieving gender parity is also a critical component of education equity. International development discussions have emphasized that equal access for girls is essential for long-term improvements in health, labor participation, and economic stability. While some regions have made substantial progress, the persistence and scale of gender disparities vary considerably. In South Asia, for example, notable increases in girls’ schooling have important implications for future demographic and economic outcomes.</p>
<p>Given these mixed patterns, our second research question <strong><em>examines whether female–male enrollment gaps have narrowed from 2000 to 2020 within the same regions.</em></strong></p>
<p>By evaluating both regional convergence and gender parity, this project seeks to provide a clearer understanding of how global education equity has evolved over the past two decades and to identify where significant challenges still remain. Our overarching goal is to assess whether the world is moving closer to universal and equitable access to education, or whether uneven progress continues to reinforce existing inequalities.</p>
</section>
<section id="data-description-cleaning" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Data Description &amp; Cleaning</h1>
<p>This project uses school enrollment data from the <strong>World Bank World Development Indicators (WDI)</strong> database. The dataset includes gross enrollment ratios for three education levels—<strong>primary</strong>, <strong>secondary</strong>, and <strong>tertiary</strong>—, total and by gender. The indicators are:</p>
<ul>
<li><strong>Primary Education</strong>
<ul>
<li>Total: <code>SE.PRM.ENRR</code></li>
<li>Male: <code>SE.PRM.ENRR.MA</code></li>
<li>Female: <code>SE.PRM.ENRR.FE</code></li>
</ul></li>
<li><strong>Secondary Education</strong>
<ul>
<li>Total: <code>SE.SEC.ENRR</code></li>
<li>Male: <code>SE.SEC.ENRR.MA</code></li>
<li>Female: <code>SE.SEC.ENRR.FE</code></li>
</ul></li>
<li><strong>Tertiary Education</strong>
<ul>
<li>Total: <code>SE.TER.ENRR</code></li>
<li>Male: <code>SE.TER.ENRR.MA</code></li>
<li>Female: <code>SE.TER.ENRR.FE</code></li>
</ul></li>
</ul>
<p>Data were collected for all available countries over the period <strong>2000–2020</strong> using the <code>wb.data.DataFrame()</code> function. The raw dataset was saved as <code>data/wdi_edu.csv</code>.</p>
<hr>
<p><strong>Here are our preprocessing steps before analysis</strong>:</p>
<section id="removal-of-missing-values" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="removal-of-missing-values"><span class="header-section-number">2.1</span> Removal of Missing Values</h2>
<p>Rows with incomplete observations across any of the enrollment indicators were removed to ensure consistent time-series data. The resulting cleaned dataset (<code>df_clean</code>) contains only complete country-year records for all twenty years.</p>
</section>
<section id="standardizing-indicator-labels" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="standardizing-indicator-labels"><span class="header-section-number">2.2</span> Standardizing Indicator Labels</h2>
<p>A mapping dictionary was applied to replace WDI indicator codes with more descriptive names such as:</p>
<ul>
<li><code>"SE.PRM.ENRR"</code> → <code>"primary"</code></li>
<li><code>"SE.PRM.ENRR.FE"</code> → <code>"primary_female"</code></li>
<li><code>"SE.SEC.ENRR.MA"</code> → <code>"secondary_male"</code></li>
<li><code>"SE.TER.ENRR"</code> → <code>"tertiary"</code></li>
</ul>
</section>
<section id="filtering-to-target-regions" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="filtering-to-target-regions"><span class="header-section-number">2.3</span> Filtering to Target Regions</h2>
<p>We filtered our data down to keep only the major global regions:</p>
<ul>
<li>Sub-Saharan Africa<br>
</li>
<li>South Asia<br>
</li>
<li>Middle East, North Africa, Afghanistan &amp; Pakistan<br>
</li>
<li>Latin America &amp; Caribbean<br>
</li>
<li>East Asia &amp; Pacific<br>
</li>
<li>Europe &amp; Central Asia<br>
</li>
<li>North America<br>
</li>
<li>World</li>
</ul>
</section>
<section id="converting-to-long-format" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="converting-to-long-format"><span class="header-section-number">2.4</span> Converting to Long Format</h2>
<p>The cleaned regional dataset was reshaped from wide to long form:</p>
<ul>
<li>Year columns (e.g., <code>"YR2000"</code>) were turned into a single <code>year</code> variable.</li>
<li><code>"YR"</code> prefixes were removed and values were converted to integers.</li>
<li>Data were sorted by <code>Country</code>, <code>series</code>, and <code>year</code>.</li>
</ul>
</section>
<section id="exporting-final-dataset" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="exporting-final-dataset"><span class="header-section-number">2.5</span> Exporting Final Dataset</h2>
<p>The final long-format dataset used for analysis was saved as <code>data/wdi_edu_filtered_long.csv</code>.</p>
<p>Here is summary statistics for the variables we have across all regions from 2000-2020:</p>
<div id="dd1fcf6f" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sqlite3</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"data/wdi_edu_filtered_long.csv"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>conn <span class="op">=</span> sqlite3.<span class="ex">connect</span>(<span class="st">"wdi_edu.db"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>df.to_sql(<span class="st">"wdi_edu"</span>, conn, if_exists<span class="op">=</span><span class="st">"replace"</span>, index<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>pd.read_sql(<span class="st">'''</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT </span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="st">    series,</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="st">    AVG(value) AS mean_rate,</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="st">    MIN(value) AS min_rate,</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="st">    MAX(value) AS max_rate</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="st">FROM wdi_edu</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="st">WHERE year BETWEEN 2000 AND 2020</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="st">GROUP BY series;</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="st">'''</span>, conn)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">series</th>
<th data-quarto-table-cell-role="th">mean_rate</th>
<th data-quarto-table-cell-role="th">min_rate</th>
<th data-quarto-table-cell-role="th">max_rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>primary</td>
<td>101.106546</td>
<td>79.473808</td>
<td>118.426079</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>primary_female</td>
<td>99.523326</td>
<td>73.061752</td>
<td>125.894310</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>primary_male</td>
<td>102.625246</td>
<td>85.790840</td>
<td>117.201439</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>secondary</td>
<td>73.880423</td>
<td>25.435600</td>
<td>105.108917</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>secondary_female</td>
<td>72.962301</td>
<td>22.674450</td>
<td>104.589317</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>secondary_male</td>
<td>74.752978</td>
<td>28.168131</td>
<td>105.600121</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>tertiary</td>
<td>36.725496</td>
<td>4.384480</td>
<td>86.950279</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>tertiary_female</td>
<td>39.691699</td>
<td>3.595470</td>
<td>101.383179</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>tertiary_male</td>
<td>33.892155</td>
<td>5.179770</td>
<td>74.362297</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
</section>
<section id="data-analysis-and-interpretation" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Data Analysis and Interpretation</h1>
<section id="growth-across-education-levels-by-region" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="growth-across-education-levels-by-region"><span class="header-section-number">3.1</span> Growth Across Education Levels by Region</h2>
<p>This table reports the average annual growth in primary, secondary, and tertiary school enrollment rates for each world region between 2000 and 2020. Growth rates are calculated as the year-to-year change in enrollment values, and then averaged over the 20-year period to capture longer-term regional trends. Positive values indicate that enrollment has generally increased over time, while negative values reflect declining or stagnant progress. Comparing growth across regions and education levels highlights where expansion in access to schooling has been fastest and where progress has been more limited.</p>
<div id="2b39328d" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>pd.read_sql(<span class="st">'''</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="st">WITH growth AS (</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="st">    SELECT</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="st">        region,</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="st">        series,</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="st">        AVG(annual_growth) AS avg_growth</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="st">    FROM (</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="st">        SELECT</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="st">            region,</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="st">            series,</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="st">            value - LAG(value) OVER (PARTITION BY region, series ORDER BY year)</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="st">                AS annual_growth</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="st">        FROM wdi_edu</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="st">        WHERE year BETWEEN 2000 AND 2020</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="st">          AND series IN ('primary','secondary','tertiary')</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="st">    ) g</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="st">    WHERE annual_growth IS NOT NULL</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="st">    GROUP BY region, series</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="st">)</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="st">    region,</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="st">    MAX(CASE WHEN series = 'primary' THEN avg_growth END) AS primary_growth,</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="st">    MAX(CASE WHEN series = 'secondary' THEN avg_growth END) AS secondary_growth,</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="st">    MAX(CASE WHEN series = 'tertiary' THEN avg_growth END) AS tertiary_growth</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="st">FROM growth</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="st">GROUP BY region</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a><span class="st">ORDER BY region;</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="st">'''</span>, conn)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">region</th>
<th data-quarto-table-cell-role="th">primary_growth</th>
<th data-quarto-table-cell-role="th">secondary_growth</th>
<th data-quarto-table-cell-role="th">tertiary_growth</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>East Asia &amp; Pacific</td>
<td>-0.508122</td>
<td>1.387767</td>
<td>1.804751</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Europe &amp; Central Asia</td>
<td>-0.166644</td>
<td>0.397700</td>
<td>1.491138</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Latin America &amp; Caribbean</td>
<td>-0.489661</td>
<td>0.886855</td>
<td>1.552549</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Middle East, North Africa, Afghanistan &amp; Pakistan</td>
<td>0.528657</td>
<td>0.525619</td>
<td>0.737428</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>North America</td>
<td>-0.031169</td>
<td>0.326427</td>
<td>0.971567</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>South Asia</td>
<td>0.233246</td>
<td>1.474988</td>
<td>0.949892</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>Sub-Saharan Africa</td>
<td>0.921688</td>
<td>0.963458</td>
<td>0.240672</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>World</td>
<td>0.025631</td>
<td>0.851748</td>
<td>1.011157</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Sub-Saharan Africa shows the fastest increase in primary enrollment, with an average annual rise of 0.92 percentage points. This suggests steady and sustained improvement in access to primary education across the region. Sub-Saharan Africa also experienced similar gains in secondary enrollment, although East Asia &amp; Pacific and South Asia outpaced all regions with even higher average yearly increases of 1.39 and 1.47, respectively. For tertiary education, East Asia &amp; Pacific, Latin America &amp; Caribbean, and the global average all exceeded 1 percentage point of growth per year, indicating particularly rapid expansion in higher education access in these regions. Taken together, these trends highlight that while basic education has been improving globally, while Sub-Saharan Africa has prioritized building strong progress at the primary level as a critical foundation for long-term educational development.</p>
</section>
<section id="enrollment-trends-over-time-across-regions-20002020" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="enrollment-trends-over-time-across-regions-20002020"><span class="header-section-number">3.2</span> Enrollment Trends Over Time Across Regions (2000–2020)</h2>
<p>To evaluate how each region compares to global progress in education access, we examine convergence in primary, secondary, and tertiary enrollment rates over the 20-year period.</p>
<p>The line graphs show how closely each region tracks the world average and whether disparities have narrowed or widened.</p>
<div id="fig-primary-line" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-primary-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/enrollment_convergence_primary.png" id="fig-primary-line" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-primary-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1
</figcaption>
</figure>
</div>
<p>As shown in <a href="#fig-primary-line" class="quarto-xref">Figure&nbsp;1</a>, primary enrollment shows clear convergence across regions. Sub-Saharan Africa and the Middle East, North Africa, Afghanistan &amp; Pakistan start well below the world average but improve steadily, reducing the gap by 2020. Latin America &amp; Caribbean remains consistently above the global level but gradually moves closer to it. The differences across regions narrow over time, indicating strong convergence at the primary level.</p>
<div id="fig-secondary-line" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-secondary-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/enrollment_convergence_secondary.png" id="fig-secondary-line" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-secondary-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2
</figcaption>
</figure>
</div>
<p>As illustrated in <a href="#fig-secondary-line" class="quarto-xref">Figure&nbsp;2</a>, progress at the secondary level is more uneven. High-performing regions such as Latin America &amp; Caribbean and East Asia &amp; Pacific rise steadily and remain above the world average. Meanwhile, South Asia, the Middle East, North Africa, Afghanistan &amp; Pakistan, and especially Sub-Saharan Africa improve more slowly and remain far below global levels. Convergence is weaker here, and substantial regional disparities persist.</p>
<div id="fig-tertiary-line" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tertiary-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/enrollment_convergence_tertiary.png" id="fig-tertiary-line" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-tertiary-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3
</figcaption>
</figure>
</div>
<p>As shown in <a href="#fig-tertiary-line" class="quarto-xref">Figure&nbsp;3</a>, tertiary enrollment displays the least convergence. Latin America &amp; Caribbean and East Asia &amp; Pacific expand rapidly and widen their advantage over other regions. The Middle East, North Africa, Afghanistan &amp; Pakistan, South Asia, and Sub-Saharan Africa improve but remain far behind. Overall, tertiary education reflects divergence rather than convergence, with inequalities growing over time.</p>
<p>The bar plots summarize how five major world regions (East Asia &amp; Pacific, Latin America &amp; Caribbean, Middle East &amp; North Africa, South Asoa, and Sub-Saharan Africa) progress across education levels. This helps reveal not only which regions are closing historical enrollment gaps but also where disparities have persisted or widened over the past two decades.</p>
<div id="fig-primary-bar" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-primary-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/enrollment_convergence_bar_primary.png" id="fig-primary-bar" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-primary-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4
</figcaption>
</figure>
</div>
<p>As shown in <a href="#fig-primary-bar" class="quarto-xref">Figure&nbsp;4</a>, Sub-Saharan Africa displays the strongest convergence toward the world average, followed by East Asia &amp; Pacific and Latin America &amp; Caribbean. The Middle East, North Africa, Afghanistan &amp; Pakistan also shows moderate improvement. South Asia slightly diverges, ending farther from the global baseline than in 2000.</p>
<div id="fig-secondary-bar" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-secondary-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/enrollment_convergence_bar_secondary.png" id="fig-secondary-bar" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-secondary-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5
</figcaption>
</figure>
</div>
<p>As seen in <a href="#fig-secondary-bar" class="quarto-xref">Figure&nbsp;5</a>, South Asia exhibits the largest improvement and closes the gap most strongly. Other regions experience smaller positive shifts, except East Asia &amp; Pacific, which diverges because its secondary enrollment rose faster than the world average.</p>
<div id="fig-tertiary-bar" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tertiary-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/enrollment_convergence_bar_tertiary.png" id="fig-tertiary-bar" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-tertiary-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6
</figcaption>
</figure>
</div>
<p><a href="#fig-tertiary-bar" class="quarto-xref">Figure&nbsp;6</a> highlights that only South Asia demonstrates meaningful convergence at the tertiary level. All other regions diverge, largely because the world average increased rapidly while regional growth lagged behind.</p>
</section>
<section id="gender-parity-in-educational-participation" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="gender-parity-in-educational-participation"><span class="header-section-number">3.3</span> Gender Parity in Educational Participation</h2>
<p>We assess the evolution of female–male enrollment disparities across five major world regions with historically lower baseline access to education: East Asia &amp; Pacific, Latin America &amp; Caribbean, the Middle East &amp; North Africa (including Afghanistan and Pakistan), South Asia, and Sub-Saharan Africa. The global average serves as a benchmark to contextualize regional progress. Gender disparities are measured using the Gender Parity Index (GPI), defined as female enrollment divided by male enrollment. A value of 1.0 represents gender parity, while values below or above 1.0 indicate male- and female-favored enrollment gaps, respectively. Our analysis examines GPI trends across three educational levels—primary, secondary, and tertiary—between 2000 and 2020.</p>
<div id="fig-gpi-primary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gpi-primary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/gpi_primary.png" id="fig-gpi-primary" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-gpi-primary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7
</figcaption>
</figure>
</div>
<p>As shown in <a href="#fig-gpi-primary" class="quarto-xref">Figure&nbsp;7</a>, primary-level GPI trends reveal substantial convergence toward gender parity across all regions. By 2020, nearly all regions are positioned within the internationally recognized near-parity threshold (0.97–1.03), including the global average, indicating that gender inequality at the point of entry into schooling has been largely eliminated. Latin America &amp; the Caribbean demonstrates a consistently slight female advantage throughout the two decades. East Asia &amp; Pacific and the world average achieved parity by the mid-2000s and maintained it thereafter. Although starting from a relatively disadvantaged position in 2000, South Asia and Sub-Saharan Africa exhibit steady and continuous improvement, closing the enrollment gap substantially by 2020. These patterns suggest that global education initiatives targeting universal primary school access have been effective in reducing structural gender exclusion in early schooling.</p>
<div id="fig-gpi-secondary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gpi-secondary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/gpi_secondary.png" id="fig-gpi-secondary" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-gpi-secondary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8
</figcaption>
</figure>
</div>
<p><a href="#fig-gpi-secondary" class="quarto-xref">Figure&nbsp;8</a> shows that while progress is evident at the secondary level, regional disparities remain more persistent than at the primary level. The world average and East Asia &amp; Pacific reached parity by approximately 2010, indicating successful transition for girls into lower-secondary education in these contexts. In contrast, South Asia and Sub-Saharan Africa continue to fall slightly below parity by the end of the time period (approximately 0.94–0.95), despite gradual improvement. The Middle East, North Africa, Afghanistan &amp; Pakistan grouping demonstrates slower convergence toward parity, reflecting continued gendered constraints during adolescence. Latin America &amp; the Caribbean sustains a female-favored balance throughout the period, suggesting comparatively stronger retention of girls beyond primary schooling. These patterns underscore the importance of the primary-to-secondary transition as a critical juncture at which gendered barriers intensify.</p>
<div id="fig-gpi-tertiary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gpi-tertiary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/gpi_tertiary.png" id="fig-gpi-tertiary" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-gpi-tertiary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9
</figcaption>
</figure>
</div>
<p>At the tertiary level, gender disparities become more pronounced and regionally divergent, as shown in <a href="#fig-gpi-tertiary" class="quarto-xref">Figure&nbsp;9</a>. The world average surpasses parity around 2010, reflecting the global expansion of women’s participation in higher education. Latin America &amp; the Caribbean experiences the strongest female advantage, exceeding a GPI of 1.30 by 2020, while East Asia &amp; Pacific and South Asia also cross parity after the mid-2010s, indicating accelerating gains in women’s university enrollment. In stark contrast, Sub-Saharan Africa remains significantly below parity throughout the period, with GPI values generally under 0.90 and only modest improvements toward the end of the decade. These persistent regional inequalities highlight the combined influence of financial pressures, limited tertiary infrastructure, and lower female completion rates at earlier levels, which collectively constrain women’s access to higher education in Sub-Saharan Africa.</p>
</section>
</section>
<section id="results-and-discussion" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Results and Discussion</h1>
<section id="regional-growth-in-enrollment-20002020" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="regional-growth-in-enrollment-20002020"><span class="header-section-number">4.1</span> <strong><em>Regional Growth in Enrollment (2000–2020)</em></strong></h2>
<p>Across the five regions analyzed, enrollment increased at all three education levels, though the pace of expansion varied considerably. Sub-Saharan Africa experienced the fastest improvement in primary enrollment, averaging nearly a one-percentage-point rise per year. At the secondary level, East Asia &amp; Pacific and South Asia recorded the largest annual gains, reflecting sustained investments in post-primary schooling. Tertiary expansion was most rapid in East Asia &amp; Pacific and Latin America &amp; Caribbean, each exceeding one percentage point of annual growth. These patterns indicate that while all regions made progress, the speed and depth of educational expansion diverged across levels.</p>
</section>
<section id="enrollment-convergence-relative-to-the-world-average" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="enrollment-convergence-relative-to-the-world-average"><span class="header-section-number">4.2</span> <strong><em>Enrollment Convergence Relative to the World Average</em></strong></h2>
<p>Line graphs of regional enrollment trajectories show substantial convergence at the primary level. Most regions began the period below or above the global average but moved closer to it over time, driven by widespread improvement in basic education. Convergence weakened at the secondary level, where disparities persisted between higher-performing regions (Latin America &amp; Caribbean, East Asia &amp; Pacific) and those lagging behind (South Asia, the Middle East, North Africa, Afghanistan &amp; Pakistan, Sub-Saharan Africa). At the tertiary level, divergence was pronounced: Latin America &amp; Caribbean and East Asia &amp; Pacific expanded rapidly, while other regions improved only modestly, widening global inequalities in higher education access. Bar plots corroborate these trends. Primary convergence was strongest for Sub-Saharan Africa and East Asia &amp; Pacific, whereas secondary convergence was driven mainly by South Asia. At the tertiary level, only South Asia showed measurable convergence; all other regions diverged from the global trend.</p>
</section>
<section id="gender-parity-in-educational-participation-1" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="gender-parity-in-educational-participation-1"><span class="header-section-number">4.3</span> <strong><em>Gender Parity in Educational Participation</em></strong></h2>
<p>Primary-level GPI values indicate near-universal movement toward gender parity across regions. By 2020, nearly all regions fall within the near-parity band (0.97–1.03). Secondary-level GPI trends show partial convergence, with Latin America &amp; Caribbean consistently favoring girls and East Asia &amp; Pacific reaching parity by the mid-2000s. In contrast, South Asia and Sub-Saharan Africa remain slightly below parity throughout, despite clear upward trajectories. At the tertiary level, gender disparities widen across regions. Latin America &amp; Caribbean and East Asia &amp; Pacific display strong female advantage, while Sub-Saharan Africa remains far below parity, indicating persistent and structural barriers preventing women’s participation in higher education.</p>
<p>The results show that while educational access has expanded worldwide, progress has been uneven across levels and regions. Primary schooling exhibits the strongest convergence, with nearly all regions approaching the world average by 2020. And this reflects the effectiveness of global initiatives aimed at universalizing basic education.</p>
<p>In contrast, secondary enrollment shows more limited convergence. Although regions such as Latin America &amp; Caribbean and East Asia &amp; Pacific maintain high participation, South Asia, the Middle East, North Africa, Afghanistan &amp; Pakistan, and Sub-Saharan Africa continue to lag behind. These persistent disparities highlight structural barriers, such as financial constraints, limited school capacity, and gendered labor expectations, that become more pronounced in adolescence.</p>
<p>Tertiary education displays the greatest divergence. Rapid expansion in East Asia &amp; Pacific and Latin America &amp; Caribbean has widened global inequalities, while other regions show much slower progress, suggesting that higher education remains closely tied to national economic capacity and long-term policy investment.</p>
<p>Gender parity patterns reinforce these trends. While most regions reach near parity at the primary level, gaps persist at secondary school and widen significantly at the tertiary level, particularly in Sub-Saharan Africa, showing that early gains for girls do not consistently translate into equal opportunities at higher levels, where financial, cultural, and institutional barriers intensify.</p>
</section>
</section>
<section id="conclusion" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Conclusion</h1>
<p>Our project examined regional enrollment growth, convergence toward global averages, and gender parity across primary, secondary, and tertiary education from 2000 to 2020. The findings show clear global progress at the foundational level: primary enrollment has expanded broadly, and most regions now achieve gender parity. However, disparities widen as education levels advance. Secondary enrollment shows mixed convergence, and tertiary education exhibits significant divergence, with only a few regions experiencing rapid expansion. Gender inequalities follow a similar pattern. While primary-level parity is nearly universal, gaps persist at the secondary level and become especially pronounced in tertiary schooling, particularly in Sub-Saharan Africa. We think results highlight that early access to education has improved substantially, but equal opportunities for advancement remain uneven. The trends suggest that achieving global education equity requires shifting attention from universal primary schooling toward strengthening secondary and tertiary systems, reducing structural barriers, and ensuring equitable gender pathways across all levels of education!</p>
</section>
<section id="references" class="level1 unnumbered" data-number="6">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">6 References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-worldbank_documents_api" class="csl-entry" role="listitem">
World Bank. (2024a). <em>World bank documents &amp; reports API portal</em>. <a href="https://documents.worldbank.org/en/publication/documents-reports/api">https://documents.worldbank.org/en/publication/documents-reports/api</a>
</div>
<div id="ref-worldbank_databank_wdi" class="csl-entry" role="listitem">
World Bank. (2024b). <em>World development indicators (WDI) DataBank</em>. <a href="https://databank.worldbank.org/source/world-development-indicators">https://databank.worldbank.org/source/world-development-indicators</a>
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>